# Generated by Django 2.1.5 on 2019-02-03 19:48

import apps.products.models
import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='naam')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('image', models.ImageField(upload_to=apps.products.models.category_image_upload, verbose_name='Afbeelding categorie')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '300x260', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='afbeelding ratio')),
                ('featured', models.BooleanField(default=False, verbose_name='voorpagina')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categorieën',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='naam')),
            ],
            options={
                'verbose_name': 'Kleur',
                'verbose_name_plural': 'Kleuren',
            },
        ),
        migrations.CreateModel(
            name='CustomerColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Nummer kleur',
                'verbose_name_plural': 'Nummers kleur',
            },
        ),
        migrations.CreateModel(
            name='CustomerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Nummer afbeelding',
                'verbose_name_plural': 'Nummers afbelding',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='prijs')),
                ('min_quantity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)], verbose_name='minimale hoeveelheid')),
                ('max_quantity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)], verbose_name='maximale hoeveelheid')),
            ],
            options={
                'verbose_name': 'Prijs',
                'verbose_name_plural': 'Prijzen',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='naam')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('custom_image', models.BooleanField(default=False, verbose_name='Klant kan een afbeelding kiezen')),
                ('custom_color', models.BooleanField(default=False, verbose_name='Klant kan een kleur kiezen')),
                ('description', ckeditor.fields.RichTextField(verbose_name='omschrijving')),
                ('extra_info', ckeditor.fields.RichTextField(verbose_name='extra informatie')),
                ('image', models.ImageField(upload_to=apps.products.models.product_image_upload, verbose_name='image from Product Detail Page')),
                ('image_home', models.ImageField(upload_to=apps.products.models.product_image_upload, verbose_name='image from Home Page')),
                ('image_category', models.ImageField(upload_to=apps.products.models.product_image_upload, verbose_name='image from Category Page')),
                ('image_related', models.ImageField(upload_to=apps.products.models.product_image_upload, verbose_name='image from Related Product list')),
                ('featured', models.BooleanField(default=False, verbose_name='voorpagina')),
                ('min_order', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)], verbose_name='minimum aantal')),
                ('category', models.ManyToManyField(blank=True, related_name='products', to='products.Category', verbose_name='categorieën')),
                ('color', models.ManyToManyField(related_name='products', to='products.Color', verbose_name='kleur')),
                ('related', models.ManyToManyField(blank=True, related_name='_product_related_+', to='products.Product', verbose_name='gerelateerde artikelen')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikelen',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='naam')),
            ],
            options={
                'verbose_name': 'Afmeting',
                'verbose_name_plural': 'Afmetingen',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(related_name='products', to='products.Size', verbose_name='afmeting'),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.Product', verbose_name='artikel'),
        ),
    ]
