# Generated by Django 2.1.5 on 2019-02-03 20:16

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '300x260', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='afbeelding ratio'),
        ),
        migrations.AddField(
            model_name='product',
            name='cropping_category',
            field=image_cropping.fields.ImageRatioField('image', '300x260', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='afbeelding ratio'),
        ),
        migrations.AddField(
            model_name='product',
            name='cropping_home',
            field=image_cropping.fields.ImageRatioField('image', '300x260', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='afbeelding ratio'),
        ),
        migrations.AddField(
            model_name='product',
            name='cropping_related',
            field=image_cropping.fields.ImageRatioField('image', '300x260', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='afbeelding ratio'),
        ),
    ]
