# Generated by Django 2.1.5 on 2019-02-06 21:43

import apps.products.models
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190203_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cropping_category',
            field=image_cropping.fields.ImageRatioField('image_category', '300x260', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='afbeelding ratio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cropping_home',
            field=image_cropping.fields.ImageRatioField('image_home', '300x260', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='afbeelding ratio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cropping_related',
            field=image_cropping.fields.ImageRatioField('image_related', '300x260', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='afbeelding ratio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=apps.products.models.product_image_upload, verbose_name='Afbeelding van Product detailpagina'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_category',
            field=models.ImageField(upload_to=apps.products.models.product_image_upload, verbose_name='Afbeelding categorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_home',
            field=models.ImageField(upload_to=apps.products.models.product_image_upload, verbose_name='Afbeelding van startpagina'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_related',
            field=models.ImageField(upload_to=apps.products.models.product_image_upload, verbose_name='Gerelateerd product'),
        ),
    ]
