# Generated by Django 2.1.5 on 2019-02-07 08:58

import ckeditor.fields
from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190206_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '270x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='afbeelding ratio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cropping_category',
            field=image_cropping.fields.ImageRatioField('image_category', '175x194', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='afbeelding ratio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cropping_home',
            field=image_cropping.fields.ImageRatioField('image_home', '225x250', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='afbeelding ratio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cropping_related',
            field=image_cropping.fields.ImageRatioField('image_related', '84x93', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='afbeelding ratio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='omschrijving'),
        ),
        migrations.AlterField(
            model_name='product',
            name='extra_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='extra informatie'),
        ),
    ]
