# Generated by Django 2.1.5 on 2019-02-07 09:20

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190207_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_home',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_related',
        ),
        migrations.AlterField(
            model_name='product',
            name='cropping_category',
            field=image_cropping.fields.ImageRatioField('image', '175x194', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='afbeelding ratio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cropping_home',
            field=image_cropping.fields.ImageRatioField('image', '225x250', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='afbeelding ratio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cropping_related',
            field=image_cropping.fields.ImageRatioField('image', '84x93', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='afbeelding ratio'),
        ),
    ]
