# Generated by Django 2.1.5 on 2019-02-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190207_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categorie', 'verbose_name_plural': 'Categorieën'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name'], 'verbose_name': 'Kleur', 'verbose_name_plural': 'Kleuren'},
        ),
        migrations.AlterModelOptions(
            name='customercolor',
            options={'ordering': ['name'], 'verbose_name': 'Nummer kleur', 'verbose_name_plural': 'Nummers kleur'},
        ),
        migrations.AlterModelOptions(
            name='customerimage',
            options={'ordering': ['name'], 'verbose_name': 'Nummer afbeelding', 'verbose_name_plural': 'Nummers afbelding'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['name'], 'verbose_name': 'Afmeting', 'verbose_name_plural': 'Afmetingen'},
        ),
    ]
