# Generated by Django 2.1.5 on 2019-02-09 10:37

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190207_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=apps.products.models.product_image_upload, verbose_name='afbeelding van Product detailpagina'),
        ),
    ]
