# Generated by Django 2.1.5 on 2019-02-03 19:48

import apps.orders.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='voornaam')),
                ('last_name', models.CharField(max_length=50, verbose_name='achternaam')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=250, verbose_name='adres')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postcode')),
                ('city', models.CharField(max_length=100, verbose_name='plaats')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_image', models.CharField(blank=True, max_length=200, null=True, verbose_name='nummer afbeelding')),
                ('custom_color', models.CharField(blank=True, max_length=200, null=True, verbose_name='nummer kleur')),
                ('product_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='artikelnaam')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='kleur')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='postcode')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='prijs')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100000)], verbose_name='aantal')),
                ('image', models.ImageField(upload_to=apps.orders.models.orders_image_upload, verbose_name='afbeelding')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order', verbose_name='order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.Product', verbose_name='artikel')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikelen',
            },
        ),
    ]
