# Generated by Django 2.1.5 on 2019-02-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remarks',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='remarks'),
        ),
    ]
