# Generated by Django 2.1.5 on 2019-02-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='remarks',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='opmerking'),
        ),
    ]
